# Generated by Django 6.0.1 on 2026-01-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0002_venue_tourdate_venue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourdate",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tourdate",
            name="ticket_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
