# Generated by Django 5.0.14 on 2026-02-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.CharField(
                choices=[
                    ("live", "Live"),
                    ("video_clip", "Video clip"),
                    ("press", "Press"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(
                help_text="Only YouTube videos will work. The video id will be extracted from given YouTube links.",
                max_length=200,
            ),
        ),
    ]
