# Generated by Django 5.0.14 on 2026-03-06 11:03

import core.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselimage",
            name="image",
            field=models.ImageField(
                upload_to=core.image_utils.hashed_upload_path,
                validators=[
                    core.image_utils.validate_image_file_size,
                    core.image_utils.validate_image_dimensions,
                    core.image_utils.validate_image_format,
                ],
            ),
        ),
    ]
