# Generated by Django 5.0.14 on 2026-03-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_carouselimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("spotify", "Spotify"),
                            ("apple_music", "Apple Music"),
                            ("soundcloud", "SoundCloud"),
                            ("deezer", "Deezer"),
                            ("youtube", "YouTube"),
                            ("bandcamp", "Bandcamp"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_links",
                        to="core.generalcontent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
