# Generated by Django 6.0.1 on 2026-01-25 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                ("cover_image", models.ImageField(upload_to="release-covers/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.URLField()),
                ("postfix", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="music.release",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StreamingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("spotify", "Spotify"),
                            ("apple_music", "Apple Music"),
                            ("youtube_music", "YouTube Music"),
                            ("amazon_music", "Amazon Music"),
                            ("tidal", "Tidal"),
                            ("deezer", "Deezer"),
                            ("bandcamp", "Bandcamp"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="music.release",
                    ),
                ),
            ],
        ),
    ]
